# fly.toml app configuration file generated for camino-del-guerrero on 2023-11-15T01:09:20-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "camino-del-guerrero"
primary_region = "gdl"

[build]

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
